@echo off
cd /d %~dp0
echo Updating Git remote URL...
git remote set-url origin https://github.com/nmultimidia/bot-tickets-infinity.git
echo Removing client_secret.json from index...
git rm --cached client_secret.json
echo Adding client_secret.json to .gitignore...
echo client_secret.json >> .gitignore
git add .gitignore
echo Committing cleanup...
git commit -m "Remove OAuth client secret file from repository"
echo DONE. Run git push --force-with-lease origin main if history cleanup is complete.
